// Generated by tools/gen-request-copy.py from Shared/RequestPage/Copy.json.
// Edit the JSON, re-run the script, commit all three. Do not edit this file.

import Foundation
import CalMirrorKit

/// The request-page UI's words. See Copy.json for why they live in one place.
enum RequestCopy {

    enum DormantRow {
        static let title = "Request page"
        static let off = "Off"
        static let blurb = "Let people ask you for a time. Nothing leaves this Mac until you turn it on."
        static let blurbPhone = "Let people ask you for a time. Nothing leaves this iPhone until you turn it on."
        static let inKeychain = "askwhen.me/%@ is yours — its key is in your iCloud Keychain. Reconnect this device and the page keeps that address."
        static let carryOn = "Reconnect"
        /// The one-liner names the device it is running on, because
        /// "nothing leaves this device" is the promise and it reads as
        /// boilerplate when the device is abstract.
        static var blurbForPlatform: String {
            #if os(macOS)
            blurb
            #else
            blurbPhone
            #endif
        }
    }

    enum Explainer {
        /// One feature row of the first-run sheet: a symbol, a headline,
        /// one line. Three of them replace the four paragraphs the explainer
        /// used to be (apple/design/native.md, section 1).
        struct Feature { let symbol: String; let headline: String; let line: String }
        static let symbol = "calendar.badge.clock"
        static let title = "A page where people can ask for a time"
        static let features: [Feature] = [
            Feature(symbol: "calendar", headline: "You choose the times", line: "A handful of offers, from the calendars you pick."),
            Feature(symbol: "lock.shield", headline: "The server never sees your calendar", line: "It holds the times you offer and the requests that come in. Nothing else."),
            Feature(symbol: "checkmark.circle", headline: "Nothing lands until you accept", line: "Every request comes to this device, and you answer it here."),
        ]
        static let footnote = "Setup is free and stays on this device. Publishing needs an AskWhen.me subscription, free for the first 90 days."
        static let primary = "Continue"
        static let secondary = "Not now"
    }

    enum Calendars {
        static let section = "Requests"
        static let blockTitle = "Block for requests"
        static let useTitle = "Use for requests"
        static let noneBlocking = "Pick at least one calendar to block, or every hour is offered."
        static let noRequestCalendar = "Pick one calendar for accepted requests."
        static let readOnly = "Read-only — accepted requests cannot be written here."
        static let footer = "Events on a blocking calendar are never offered, and accepted requests are written to the one calendar you mark. Only busy or free is ever read."
    }

    enum Display {
        static let section = "Your page"
        static let nameTitle = "Display name"
        static let namePlaceholder = "Matt Baylor"
        static let blurbTitle = "One line about it"
        static let blurbPlaceholder = "30 minutes, usually about refereeing or calendars."
        static let meetingSection = "When you accept"
        static let titleTitle = "Event title"
        static let titlePlaceholder = "Meeting"
        static let locationTitle = "Location"
        static let locationPlaceholder = "Optional — a room, or a link"
        static let nameMissing = "A page needs a name."
        static let pageFooter = "Your name is the only thing on the page that identifies you; any label works."
        static let meetingFooter = "You title the event and the person’s note goes in it; the location goes into the event and the calendar file they receive."
    }

    enum Policy {
        static let section = "Your day"
        static let dayStarts = "My day starts at"
        static let dayEnds = "and ends at"
        static let zoneTitle = "Time zone"
        static let lunchTitle = "Keep a gap clear"
        static let weekdaysTitle = "Offer on"
        static let horizonTitle = "How far ahead"
        static let noticeTitle = "Notice I need"
        static let maxPerDayTitle = "Most requests a day"
        static let slotTitle = "How long an offer is"
        static let alignTitle = "Start times land on"
        static let bufferTitle = "Keep clear either side"
        static let dayFooter = "Times are in the zone you state, wherever this device travels. The next screen shows what this offers on real dates."
        static let shapeFooter = "Both are privacy controls: a shorter horizon and a lower cap show less of your week’s shape."
        static let noticeFooter = "Nothing inside this window is offered, so a request never lands with less warning than this device needs."
        static let offerFooter = "Each offer is this long, starts on this grid, and keeps this much clear of anything real in your calendar."
    }

    enum Notification {
        static let categoryId = "askwhen.request"
        static let acceptId = "askwhen.accept"
        static let declineId = "askwhen.decline"
        static let accept = "Accept"
        static let decline = "Decline"
        static let titleFormat = "%@ asked for a time"
        static let bodyNoNote = "%@"
        static let bodyWithNote = "%@\n%@"
        static let acceptedTitle = "Accepted"
        static let acceptedBody = "%@ is in your calendar. They have been sent the details."
        static let declinedTitle = "Declined"
        static let declinedBody = "%@ has been told, and the time is free again."
        static let conflictTitle = "Could not accept — that time is taken"
        static let conflictBody = "Something landed on %@ since it was offered. Nothing was written. Open Calendar Mirror to see the alternatives."
        static let failedTitle = "Accepted, but AskWhen.me was not told"
        static let failedBody = "The event is in your calendar. The person who asked has not been sent it yet — open the app to finish."
        static let permissionHeading = "Notifications"
        static let permissionAsk = "Allow notifications"
        static let permissionSkip = "Not now"
        static let permissionDenied = "Off for Calendar Mirror. Requests still wait in the app; Settings › Notifications turns them back on."
        static let permissionFooter = "A notification is how you find out a request is waiting, and it carries Accept and Decline. The person’s name and note appear in it."
    }

    enum Conflict {
        static let title = "That time is taken"
        static let lede = "%@ asked for %@, and something has landed on it since you offered it. Nothing has been written, and nobody has been told anything yet."
        static let landedHeading = "What is on it now"
        static let landedFormat = "%@ — %@"
        static let landedAllDay = "An all-day event on %@"
        static let landedNote = "Shown as a time only. This is the same busy/free view the page is built from — the app does not read what your events are called."
        static let alternativesHeading = "Nearest times still open"
        static let alternativesNote = "Declining tells them the time is gone. There is no way to offer one of these back to them from here — they would have to ask again — so if one of these works, say so when you reply."
        static let noAlternatives = "Nothing else is open inside your horizon. Declining is the honest answer."
        static let acceptAnyway = "Accept anyway"
        static let acceptAnywayNote = "Writes it into your calendar on top of whatever is there. Sometimes that is exactly right — you know what the clash is and this matters more."
        static let decline = "Decline"
        static let later = "Leave it for now"
        static let laterNote = "It stays in your queue. The time is held for whoever asked until the hold runs out, and then the slot goes back on offer."
    }

    enum Lapse {
        static let graceHeading = "Your subscription has ended"
        static let graceBody = "Your page is still there, but it is not taking requests. Anyone who opens it sees “not currently taking requests” — the same line it shows when your device has been offline for a while, so it does not announce anything about you."
        static let graceCountOne = "It is deleted in 1 day."
        static let graceCountMany = "It is deleted in %d days."
        static let graceWhatGoes = "When that happens the page, its address and anything still in its queue are removed, and the link 404s. Your calendar is untouched — every request you already accepted is an ordinary event and stays exactly where it is."
        static let graceFix = "Renewing inside the grace brings the same page back at the same address, so the links you have sent out keep working."
        static let renew = "Renew"
        static let revokedHeading = "Your subscription was refunded"
        static let revokedBody = "Apple has reversed the purchase, so there is no grace period — the page has stopped taking requests now. Subscribing again creates a new page at a new address."
        static let goneHeading = "Your page has been deleted"
        static let goneBody = "The grace period ended and AskWhen.me removed the page. Links to the old address no longer work, and there is nothing left to restore — a new subscription starts a new page with a new address."
        static let goneCalendar = "Everything you accepted is still in your calendar. Nothing that was already agreed depended on the page staying up."
        static let startAgain = "Start a new page"
        static let bannerGrace = "Not taking requests — deleted in %d days"
        static let bannerRevoked = "Not taking requests"
        static let bannerGone = "Page deleted"
    }

    enum Domains {
        static let section = "Address"
        static let current = "Your page is at"
        static let slugNote = "This address always works and is never taken away, whatever else you add."
        static let subdomainHeading = "Your own name on AskWhen.me"
        static let subdomainBody = "Something like dana.askwhen.me. Nothing to set up — it works the moment you claim it."
        static let subdomainPlaceholder = "dana"
        static let subdomainSuffix = ".askwhen.me"
        static let claim = "Claim it"
        static let customHeading = "A domain you own"
        static let customBody = "Something like ask.yourcompany.com, on a domain you already control. It needs one DNS record, and the certificate is issued for you."
        static let customPlaceholder = "ask.yourcompany.com"
        static let cnameHeading = "Add this record"
        static let cnameFormat = "CNAME   %@   →   %@"
        static let cnameNote = "Add it wherever your domain's DNS lives, then come back and check. It usually works within a few minutes, sometimes an hour."
        static let checking = "Checking DNS…"
        static let check = "Check now"
        static let checkNote = "Checking is what makes it start working — the service re-reads DNS every time you ask, and issues the certificate the moment the record is right."
        static let verified = "Working"
        static let pending = "Waiting for DNS"
        static let sawHeading = "What DNS says right now"
        static let release = "Stop using this address"
        static let releaseNote = "The address stops working immediately and anyone holding a link to it loses it. Your askwhen.me/… address is unaffected."
        static let needsSubdomainTier = "Your own subdomain comes with the Custom Subdomain tier, which also lets you have more than one page."
        static let needsDomainTier = "Using a domain you own comes with the Custom Domain tier."
        static let upgrade = "Upgrade"
        static let upgradeNote = "An upgrade is charged straight away, with what is left of this year credited against it. Apple handles the arithmetic and shows you the number before you agree."
        static let taken = "That address is already claimed."
        static let failed = "AskWhen.me did not answer. Nothing was claimed — try again."
    }

    enum SendTimes {
        static let row = "Send times"
        static let footer = "Your next three free times as a message, in your time zone, with your page’s link if you have one."
        static let menu = "Copy Times to Send"
        static let copied = "Copied: %@"
        static let empty = "Nothing free to offer in the next %d days."
        static let footerPage = "Whoever you send this to can take one of these times. It lands in your calendar if the time is still clear."
    }

    enum Live {
        static let section = "Your page"
        static let heading = "Your page is live"
        static let lede = "Send this link to anyone who should be able to ask you for a time."
        static let linkFooter = "Nothing for them to install and no account for them to make."
        static let share = "Share link"
        static let openTitle = "Open it"
        static let deviceSection = "This device"
        static let publishes = "Publishes your page"
        static let holdsKey = "Key in your iCloud Keychain"
        static let deviceFooter = "Other devices can answer requests; only this one publishes. The page’s key is in your iCloud Keychain, so a new device or a reinstall finds it. Switching off stops publishing at once."
        static let turnOff = "Request page"
        static let notPublished = "Nothing has been published yet — the first upload happens on the next sync."
    }

    enum Offer {
        static let section = "Publishing"
        static let heading = "Publish your page"
        static let lede = "Everything so far has stayed on this device. Publishing puts the times you previewed on AskWhen.me."
        static let network = "Loading the price is this app’s first contact with anyone — Apple, for the price in your currency. AskWhen.me is not involved yet."
        static let loading = "Asking Apple for the price…"
        static let purchasing = "Waiting for Apple…"
        static let failedTitle = "Could not reach the App Store"
        static let failedBody = "Apple did not answer, so there is no price to show. Your page is still here, on this device."
        static let retry = "Try again"
        static let trialLine = "%@, then %@ a year."
        static let noTrialLine = "%@ a year."
        static let noTrialNote = "Apple gives one free trial per person, and you have used yours. The price below is what it costs from today."
        static let buyWithTrial = "Start the free trial"
        static let buyWithoutTrial = "Subscribe"
        static let renews = "Renews yearly until you cancel in Settings. Nothing is charged during the trial."
        static let upgradesHeading = "If you need more later"
        static let upgradesNote = "Upgrades, whenever you want one. Neither carries a trial."
        static let restore = "Restore Purchases"
        static let restoring = "Checking with Apple…"
        static let restoredNone = "Apple has no subscription on file for this Apple Account."
        static let cancelled = "Nothing was bought and nothing changed."
        static let pendingTitle = "Waiting for approval"
        static let pendingBody = "Apple is holding this for approval. The moment it clears, your page publishes itself."
        static let alreadyTitle = "You already subscribe"
        static let alreadyBody = "This Apple Account already has an AskWhen.me subscription. Publishing is the only step left."
        static let publish = "Publish my page"
        static let creating = "Creating your page…"
        static let createFailedTitle = "Apple said yes, AskWhen.me did not answer"
        static let createFailedBody = "Your subscription went through and you will not be charged twice. Try again; nothing is lost."
        static let tokenWarning = "The page’s key goes into your iCloud Keychain, so a new device finds it. There is no account and no password."
    }

    enum Preview {
        static let section = "What people see"
        static let countOne = "%d time"
        static let countMany = "%d times"
        static let across = "across %d days"
        static let emptyPage = "Your page would be empty — the reasons are on each day below."
        static let privacy = "A gap could be a meeting, your lunch or your daily cap; the page never says which."
        static let emptyDayHeading = "Days offering nothing"
        static let whyHeading = "Why"
        static let cappedNote = "Times you could have offered and chose not to."
        static let stale = "Calculated just now from this device. Nothing has been published."

        /// Why individual candidates were dropped. Lower-case
        /// fragments — they are joined into a sentence.
        static func reason(_ r: Rejection) -> String {
            switch r {
            case .clockSkipped: return "the clock skips that hour"
            case .pastDayEnd: return "would run past the end of your day"
            case .minimumNotice: return "inside your notice window"
            case .lunch: return "your lunch gap"
            case .busy: return "busy"
            case .cappedPerDay: return "over your daily cap"
            }
        }

        /// Why a whole day was excluded before any time was considered.
        static func reason(_ r: DayRejection) -> String {
            switch r {
            case .weekdayNotOffered: return "You do not offer this weekday."
            case .blackoutDate: return "You blacked this date out."
            case .allDayEvent: return "An all-day event covers it."
            case .dayUnavailable: return "This device could not resolve the day."
            }
        }

        /// Why the policy itself offers nothing, whatever the calendar says.
        static func reason(_ p: PolicyProblem) -> String {
            switch p {
            case .unknownTimeZone: return "This device does not know the zone your policy names, so nothing is offered at all. Pick the zone again."
            case .dayWindowInvalid: return "The start and end of your day do not make a usable window."
            case .maxPerDayNotPositive: return "Your daily cap is zero, so nothing can be offered."
            }
        }
    }
}
