// Generated by tools/gen-request-copy.py from Shared/RequestPage/Copy.json.
// Edit the JSON, re-run the script, commit all three. Do not edit this file.

import Foundation

/// The request-page UI's words. See Copy.json for why they live in one place.
enum RequestCopy {

    enum DormantRow {
        static let title = "Request page"
        static let off = "Off"
        static let blurb = "Let people ask you for a time. Nothing leaves this Mac until you turn it on."
        static let blurbPhone = "Let people ask you for a time. Nothing leaves this iPhone until you turn it on."
        /// The one-liner names the device it is running on, because
        /// "nothing leaves this device" is the promise and it reads as
        /// boilerplate when the device is abstract.
        static var blurbForPlatform: String {
            #if os(macOS)
            blurb
            #else
            blurbPhone
            #endif
        }
    }

    enum Explainer {
        static let title = "A page where people can ask for a time"
        static let paragraphs: [String] = [
            "You offer a handful of times you are willing to be asked about. Someone opens your page, picks one, and tells you who they are.",
            "Nothing lands in your calendar until you accept. Every request comes to this device and you answer it here — askwhen.me cannot write to your calendar, because you never give it access.",
            "Turning this on means a server holds two things: the times you chose to offer, and requests from people who asked for one. It never sees your calendar, your events, your address, or your name beyond the label you pick.",
        ]
        static let costHeading = "What it costs"
        static let cost = "Setting it up is free and happens entirely on this device. Publishing a page needs a subscription — free for the first 90 days — and that comes at the end, after you have seen the page you would be publishing."
        static let primary = "Set up a request page"
        static let footnote = "Nothing has been sent anywhere. Setting this up does not send anything either — the first time this app touches the network is the moment you ask to see the price."
    }

    enum Calendars {
        static let section = "Requests"
        static let blockTitle = "Block for requests"
        static let blockCaption = "Events here make you unavailable, so no time that clashes with one is ever offered. Turn this on for every calendar that holds real commitments."
        static let useTitle = "Use for requests"
        static let useCaption = "Requests you accept are written here as ordinary events. Exactly one calendar."
        static let privacy = "Only the busy-or-free shape of these calendars is ever read. Titles, locations, attendees, notes and which calendar an event came from stop at this device and are never published."
        static let noneBlocking = "No calendar is blocking yet, so every hour in your day would be offered. Pick at least one."
        static let noRequestCalendar = "Pick one calendar for accepted requests to be written into."
        static let readOnly = "Read-only — accepted requests cannot be written here."
    }
}
