// Generated by tools/gen-request-copy.py from Shared/RequestPage/Copy.json.
// Edit the JSON, re-run the script, commit all three. Do not edit this file.

import Foundation
import CalMirrorKit

/// The request-page UI's words. See Copy.json for why they live in one place.
enum RequestCopy {

    enum DormantRow {
        static let title = "Request page"
        static let off = "Off"
        static let blurb = "Let people ask you for a time. Nothing leaves this Mac until you turn it on."
        static let blurbPhone = "Let people ask you for a time. Nothing leaves this iPhone until you turn it on."
        /// The one-liner names the device it is running on, because
        /// "nothing leaves this device" is the promise and it reads as
        /// boilerplate when the device is abstract.
        static var blurbForPlatform: String {
            #if os(macOS)
            blurb
            #else
            blurbPhone
            #endif
        }
    }

    enum Explainer {
        static let title = "A page where people can ask for a time"
        static let paragraphs: [String] = [
            "You offer a handful of times you are willing to be asked about. Someone opens your page, picks one, and tells you who they are.",
            "Nothing lands in your calendar until you accept. Every request comes to this device and you answer it here — askwhen.me cannot write to your calendar, because you never give it access.",
            "Turning this on means a server holds two things: the times you chose to offer, and requests from people who asked for one. It never sees your calendar, your events, your address, or your name beyond the label you pick.",
        ]
        static let costHeading = "What it costs"
        static let cost = "Setting it up is free and happens entirely on this device. Publishing a page needs a subscription — free for the first 90 days — and that comes at the end, after you have seen the page you would be publishing."
        static let primary = "Set up a request page"
        static let footnote = "Nothing has been sent anywhere. Setting this up does not send anything either — the first time this app touches the network is the moment you ask to see the price."
    }

    enum Calendars {
        static let section = "Requests"
        static let blockTitle = "Block for requests"
        static let blockCaption = "Events here make you unavailable, so no time that clashes with one is ever offered. Turn this on for every calendar that holds real commitments."
        static let useTitle = "Use for requests"
        static let useCaption = "Requests you accept are written here as ordinary events. Exactly one calendar."
        static let privacy = "Only the busy-or-free shape of these calendars is ever read. Titles, locations, attendees, notes and which calendar an event came from stop at this device and are never published."
        static let noneBlocking = "No calendar is blocking yet, so every hour in your day would be offered. Pick at least one."
        static let noRequestCalendar = "Pick one calendar for accepted requests to be written into."
        static let readOnly = "Read-only — accepted requests cannot be written here."
    }

    enum Display {
        static let section = "Your page"
        static let nameTitle = "Display name"
        static let namePlaceholder = "Matt Baylor"
        static let nameCaption = "Required, and the only thing on your page that identifies you — everything else a visitor sees is a list of times. Any label works: your name, your initials, or what you do. You decide how much that discloses."
        static let blurbTitle = "One line about it"
        static let blurbPlaceholder = "30 minutes, usually about refereeing or calendars."
        static let blurbCaption = "Sits under your name. Anyone with the link reads it, so keep it to what the time is for."
        static let meetingSection = "When you accept"
        static let titleTitle = "Event title"
        static let titlePlaceholder = "Meeting"
        static let titleCaption = "What the event is called in your calendar. You choose it, never the person asking — a stranger's words do not become a title in your calendar. What they write goes in the event's notes, where it is obviously theirs."
        static let locationTitle = "Location"
        static let locationPlaceholder = "Optional — a room, or a link"
        static let locationCaption = "Goes into the event and into the calendar file the person receives, so whoever you accept will see it."
        static let nameMissing = "A page needs a name. Without one it looks like a form asking a stranger for their email address, which is what a phishing page looks like too."
    }

    enum Policy {
        static let section = "Your day"
        static let sentence = "Answer it the way you would say it out loud. The preview underneath shows real dates, so a mistake is visible before anyone else sees it."
        static let dayStarts = "My day starts at"
        static let dayEnds = "and ends at"
        static let zoneTitle = "Time zone"
        static let zoneCaption = "Stated, not guessed from this device. A laptop that travels must not quietly re-read “my day starts at 9” as 9am somewhere else."
        static let lunchTitle = "Keep a gap clear"
        static let lunchCaption = "One mid-day gap. A list of arbitrary exclusions would be a second calendar wearing a disguise — put those in a blocking calendar instead."
        static let weekdaysTitle = "Offer on"
        static let horizonTitle = "How far ahead"
        static let horizonCaption = "How far out someone can ask. A longer horizon puts more of your future shape on one screen, so this is a privacy control as much as an accuracy one. Between 2 and 45 days; beyond that the times are fiction, because calendars fill."
        static let noticeTitle = "Notice I need"
        static let noticeCaption = "Nothing inside this window is offered. It guards against a request landing with less warning than your device needs to collect it."
        static let maxPerDayTitle = "Most requests a day"
        static let maxPerDayCaption = "This matters more than it looks. Publishing every free half-hour tells a stranger your week is empty; offering four says nothing about the other twelve."
        static let slotTitle = "How long an offer is"
        static let slotCaption = "The same number becomes the meeting length on your page and in the calendar file you send."
        static let alignTitle = "Start times land on"
        static let alignCaption = "Offers begin on a multiple of this past the hour, so people see :00 and :30 rather than :07. Only values that divide into 60 are offered, because the others walk through the hour."
        static let bufferTitle = "Keep clear either side"
        static let bufferCaption = "Held free around anything real in your calendar, so nothing lands wheel-to-wheel against a meeting the person asking cannot see."
    }

    enum Live {
        static let section = "Your page"
        static let heading = "Your page is live"
        static let lede = "Send this link to anyone you want to be able to ask you for a time. There is nothing for them to install and no account for them to make."
        static let copy = "Copy link"
        static let copied = "Copied"
        static let openTitle = "Open it"
        static let openNote = "Worth looking at once, the way the people you send it to will see it."
        static let tokenHeading = "This device holds the only key"
        static let tokenBody = "Your page is kept alive by a key stored in this device's keychain. There is no account and no password, so nobody — including us — can email it to you or recover it. If you lose this device you make a new page and send out a new link."
        static let publisherHeading = "This device publishes"
        static let publisherBody = "It derives the times and uploads them whenever your calendar changes. Your other devices can still collect requests and answer them; only this one publishes, so two devices can never disagree about when you are free."
        static let offHeading = "Turning it off"
        static let offBody = "Switching the request page off stops publishing immediately and the page goes dark. Your subscription is Apple's to cancel, in Settings."
        static let turnOff = "Turn off the request page"
        static let notPublished = "Nothing has been published yet — the first upload happens on the next sync."
    }

    enum Offer {
        static let section = "Publishing"
        static let heading = "Publish your page"
        static let lede = "Everything so far has stayed on this device. Publishing puts the times you just previewed on askwhen.me, where the people you send the link to can ask for one."
        static let network = "Loading the price is the first time this app has contacted anyone. It asks Apple what a subscription costs in your currency — nothing about you, your calendar or your page is sent, and askwhen.me is still not involved."
        static let loading = "Asking Apple for the price…"
        static let failedTitle = "Could not reach the App Store"
        static let failedBody = "Apple did not answer, so there is no price to show. Nothing is wrong with your page — it is still here, still on this device. Try again when you have a connection."
        static let retry = "Try again"
        static let trialLine = "%@, then %@ a year."
        static let noTrialLine = "%@ a year."
        static let noTrialNote = "Apple gives one free trial per person, and you have used yours. The price below is what it costs from today."
        static let buyWithTrial = "Start the free trial"
        static let buyWithoutTrial = "Subscribe"
        static let renews = "Renews yearly until you cancel. Cancel any time in Settings — during the free trial nothing is charged at all."
        static let upgradesHeading = "If you need more later"
        static let upgradesNote = "Both of these are upgrades you can take whenever you want one. Neither carries a free trial, and neither is worth buying before you have a page — a nicer address is not much use without something at it."
        static let restore = "Restore Purchases"
        static let restoring = "Checking with Apple…"
        static let restoredNone = "Apple has no subscription on file for this Apple Account."
        static let cancelled = "No problem — nothing was bought and nothing changed. Your page is still here whenever you want it."
        static let pendingTitle = "Waiting for approval"
        static let pendingBody = "Apple is holding this until someone approves it — Ask to Buy, or a payment method that needs confirming. The moment it clears, your page publishes itself. You can close the app."
        static let alreadyTitle = "You already subscribe"
        static let alreadyBody = "This Apple Account has an active AskWhen.me subscription, so there is nothing to buy. Publishing your page is the only step left."
        static let publish = "Publish my page"
        static let creating = "Creating your page…"
        static let createFailedTitle = "Apple said yes, askwhen.me did not answer"
        static let createFailedBody = "Your subscription went through — you have not been charged twice and you will not be. The page itself could not be created just now. Try again; nothing is lost and nothing is duplicated."
        static let tokenWarning = "Your page is kept alive by a key held only on this device, in its keychain. There is no account and no password, so it cannot be emailed to you or recovered — if you lose this device, you make a new page."
    }

    enum Preview {
        static let section = "What people see"
        static let headingOne = "You are offering %d time across %d days"
        static let headingMany = "You are offering %d times across %d days"
        static let emptyPage = "Your page would be empty. Nobody can ask you for anything until something is offered — the reasons are on each day below."
        static let privacy = "A gap on your page could be a meeting, your lunch, a day you blacked out, or simply your daily cap. Nothing on the page says which, and that is the point."
        static let emptyDayHeading = "Days offering nothing"
        static let whyHeading = "Why"
        static let cappedNote = "Times you could have offered and chose not to. That is a different answer to “why is nothing showing” than being busy."
        static let stale = "Calculated just now from the calendars on this device. Nothing here has been published."

        /// Why individual candidates were dropped. Lower-case
        /// fragments — they are joined into a sentence.
        static func reason(_ r: Rejection) -> String {
            switch r {
            case .clockSkipped: return "the clock skips that hour"
            case .pastDayEnd: return "would run past the end of your day"
            case .minimumNotice: return "inside your notice window"
            case .lunch: return "your lunch gap"
            case .busy: return "busy"
            case .cappedPerDay: return "over your daily cap"
            }
        }

        /// Why a whole day was excluded before any time was considered.
        static func reason(_ r: DayRejection) -> String {
            switch r {
            case .weekdayNotOffered: return "You do not offer this weekday."
            case .blackoutDate: return "You blacked this date out."
            case .allDayEvent: return "An all-day event covers it."
            case .dayUnavailable: return "This device could not resolve the day."
            }
        }

        /// Why the policy itself offers nothing, whatever the calendar says.
        static func reason(_ p: PolicyProblem) -> String {
            switch p {
            case .unknownTimeZone: return "This device does not know the zone your policy names, so nothing is offered at all. Pick the zone again."
            case .dayWindowInvalid: return "The start and end of your day do not make a usable window."
            case .maxPerDayNotPositive: return "Your daily cap is zero, so nothing can be offered."
            }
        }
    }
}
