#!/usr/bin/env python3
"""Generate the request-page copy constants and the review contact sheet.

One source (`Shared/RequestPage/Copy.json`), two outputs:

  Shared/RequestPage/Copy.swift   what the app shows
  tools/contact-sheet.html        what Matt marks up

The point of generating both is that a mockup which can drift from the app is
worth less than no mockup at all — you review the wrong words and ship the
right ones. CI runs this and diffs, exactly as the web app does with the dump's
generated type, so the two cannot separate silently.

What the sheet is NOT: a screenshot. It cannot be, because this repository's
UI is SwiftUI and the sheet is HTML. It shows the words, the order, the
control types and the true width. Pixel truth comes from the simulator on a
Mac, and nothing here should be trusted about spacing, type or colour.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "Shared" / "RequestPage" / "Copy.json"
SWIFT = ROOT / "Shared" / "RequestPage" / "Copy.swift"
SHEET = ROOT / "tools" / "contact-sheet.html"

BANNER = "// Generated by tools/gen-request-copy.py from Shared/RequestPage/Copy.json.\n// Edit the JSON, re-run the script, commit all three. Do not edit this file.\n"


def swift_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def gen_swift(c: dict) -> str:
    out = [BANNER, "\nimport Foundation\n",
           "\n/// The request-page UI's words. See Copy.json for why they live in one place.\n",
           "enum RequestCopy {\n"]

    d = c["dormantRow"]
    out.append("\n    enum DormantRow {\n")
    for k in ("title", "off", "blurb", "blurbPhone"):
        out.append(f"        static let {k} = {swift_string(d[k])}\n")
    out.append("        /// The one-liner names the device it is running on, because\n")
    out.append("        /// \"nothing leaves this device\" is the promise and it reads as\n")
    out.append("        /// boilerplate when the device is abstract.\n")
    out.append("        static var blurbForPlatform: String {\n")
    out.append("            #if os(macOS)\n            blurb\n            #else\n            blurbPhone\n            #endif\n        }\n    }\n")

    e = c["explainer"]
    out.append("\n    enum Explainer {\n")
    out.append(f"        static let title = {swift_string(e['title'])}\n")
    out.append("        static let paragraphs: [String] = [\n")
    for p in e["paragraphs"]:
        out.append(f"            {swift_string(p)},\n")
    out.append("        ]\n")
    for k in ("costHeading", "cost", "primary", "footnote"):
        out.append(f"        static let {k} = {swift_string(e[k])}\n")
    out.append("    }\n")

    cal = c["calendars"]
    out.append("\n    enum Calendars {\n")
    for k in ("section", "blockTitle", "blockCaption", "useTitle", "useCaption",
              "privacy", "noneBlocking", "noRequestCalendar", "readOnly"):
        out.append(f"        static let {k} = {swift_string(cal[k])}\n")
    out.append("    }\n}\n")
    return "".join(out)


def row(title, caption=None, control="toggle", value=None):
    ctl = {
        "toggle": '<span class="ctl toggle" aria-hidden="true"></span>',
        "check": '<span class="ctl check" aria-hidden="true">✓</span>',
        "chevron": '<span class="ctl chev" aria-hidden="true">›</span>',
        "none": "",
    }[control]
    val = f'<span class="val">{esc(value)}</span>' if value else ""
    cap = f'<p class="cap">{esc(caption)}</p>' if caption else ""
    return (f'<div class="row"><div class="rowmain"><span class="t">{esc(title)}</span>'
            f'{val}{ctl}</div>{cap}</div>')


def gen_sheet(c: dict) -> str:
    d, e, cal = c["dormantRow"], c["explainer"], c["calendars"]

    s1 = ('<div class="scr"><div class="nav">Calendar Mirror</div>'
          '<div class="grp">'
          + row("Run no sooner than", None, "none", "30 minutes")
          + '</div><div class="grp">'
          + row(d["title"], d["blurbPhone"], "chevron", d["off"])
          + "</div></div>")

    paras = "".join(f'<p class="body">{esc(p)}</p>' for p in e["paragraphs"])
    s2 = ('<div class="scr"><div class="nav"><span class="back">‹ Back</span></div>'
          f'<div class="pad"><h3>{esc(e["title"])}</h3>{paras}'
          f'<p class="sub">{esc(e["costHeading"])}</p>'
          f'<p class="body">{esc(e["cost"])}</p>'
          f'<div class="btn">{esc(e["primary"])}</div>'
          f'<p class="foot">{esc(e["footnote"])}</p></div></div>')

    cals = [("Home", True, False), ("Work", True, False),
            ("Referee assignments", True, True), ("US Holidays", False, False)]
    rows = ""
    for name, blocking, isreq in cals:
        rows += (f'<div class="calrow"><span class="t">{esc(name)}</span>'
                 f'<span class="pill {"on" if blocking else ""}">{esc(cal["blockTitle"])}</span>'
                 f'<span class="pill {"on" if isreq else ""}">{esc(cal["useTitle"])}</span></div>')
    s3 = ('<div class="scr"><div class="nav">Manage Mirrors</div>'
          f'<div class="grp"><div class="hdr">{esc(cal["section"])}</div>{rows}'
          f'<p class="cap pad8">{esc(cal["blockCaption"])}</p>'
          f'<p class="cap pad8">{esc(cal["useCaption"])}</p>'
          f'<p class="cap pad8 priv">{esc(cal["privacy"])}</p></div></div>')

    cells = [
        ("1 · The dormant row", "Off by default. Drawing this costs no network.", s1),
        ("2 · What this is", "The opt-in. Names the cost up front so screen 7 is not a surprise.", s2),
        ("3 · Which calendars count", "Two checkboxes per calendar, where the owner already is.", s3),
    ]
    body = "".join(
        f'<div class="cell"><h2>{esc(t)}</h2><p>{esc(sub)}</p>{scr}</div>'
        for t, sub, scr in cells)

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Request page — contact sheet</title>
    <!-- GENERATED by tools/gen-request-copy.py. Edit Shared/RequestPage/Copy.json. -->
    <style>
      :root {{
        color-scheme: light dark;
        --page: #e8ecf3; --ink: #0d1220; --note: #5a6a80; --edge: #cfd8e6;
        --card: #ffffff; --grp: #f2f3f7; --tint: #0a63d2; --sep: #e3e6ee;
      }}
      @media (prefers-color-scheme: dark) {{
        :root {{
          --page: #06080d; --ink: #e6edf3; --note: #8494a8; --edge: #1c2432;
          --card: #11151d; --grp: #171c26; --tint: #4c9bff; --sep: #232b38;
        }}
      }}
      body {{ margin: 0; background: var(--page); color: var(--ink); padding: 32px 24px 64px;
        font: 15px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }}
      h1 {{ font-size: 20px; margin: 0 0 4px; }}
      .lede {{ color: var(--note); margin: 0 0 8px; max-width: 74ch; }}
      .warn {{ color: var(--note); margin: 0 0 30px; max-width: 74ch; font-size: 13px;
        border-left: 3px solid var(--edge); padding-left: 10px; }}
      #sheet {{ display: grid; grid-template-columns: repeat(auto-fill, 390px);
        justify-content: start; gap: 30px 26px; align-items: start; }}
      .cell h2 {{ font-size: 13px; text-transform: uppercase; letter-spacing: .6px; margin: 0 0 2px; }}
      .cell > p {{ color: var(--note); font-size: 13px; margin: 0 0 10px; }}
      /* 390px is the iPhone 15/16 logical width. Fixed, never stretched: a
         contact sheet whose frames resize is lying about the phone. */
      .scr {{ width: 390px; box-sizing: border-box; background: var(--grp);
        border: 1px solid var(--edge); border-radius: 12px; overflow: hidden; }}
      .nav {{ padding: 12px 16px; font-weight: 600; font-size: 17px;
        border-bottom: 1px solid var(--sep); background: var(--card); }}
      .back {{ color: var(--tint); font-weight: 400; font-size: 16px; }}
      .grp {{ background: var(--card); margin: 14px 0; border-top: 1px solid var(--sep);
        border-bottom: 1px solid var(--sep); }}
      .hdr {{ font-size: 12px; text-transform: uppercase; letter-spacing: .5px;
        color: var(--note); padding: 14px 16px 6px; }}
      .row {{ padding: 11px 16px; border-bottom: 1px solid var(--sep); }}
      .row:last-child {{ border-bottom: 0; }}
      .rowmain {{ display: flex; align-items: center; gap: 8px; }}
      .t {{ flex: 1; }}
      .val {{ color: var(--note); }}
      .ctl.toggle {{ width: 42px; height: 25px; border-radius: 13px; background: var(--sep); }}
      .ctl.chev {{ color: var(--note); font-size: 20px; }}
      .cap {{ color: var(--note); font-size: 12.5px; margin: 6px 0 0; }}
      .pad8 {{ padding: 0 16px 10px; }}
      .priv {{ border-top: 1px solid var(--sep); padding-top: 10px; }}
      .pad {{ padding: 18px 20px 24px; background: var(--card); }}
      h3 {{ font-size: 24px; line-height: 1.2; margin: 4px 0 14px; }}
      .body {{ font-size: 15px; margin: 0 0 12px; }}
      .sub {{ font-size: 12px; text-transform: uppercase; letter-spacing: .5px;
        color: var(--note); margin: 20px 0 6px; }}
      .btn {{ background: var(--tint); color: #fff; text-align: center; padding: 14px;
        border-radius: 10px; font-weight: 600; margin: 22px 0 12px; }}
      .foot {{ color: var(--note); font-size: 12.5px; margin: 0; }}
      .calrow {{ display: flex; align-items: center; gap: 6px; padding: 10px 16px;
        border-bottom: 1px solid var(--sep); }}
      .pill {{ font-size: 11px; padding: 3px 8px; border-radius: 99px; white-space: nowrap;
        border: 1px solid var(--sep); color: var(--note); }}
      .pill.on {{ background: var(--tint); border-color: var(--tint); color: #fff; }}
    </style>
  </head>
  <body>
    <h1>Request page — setup, screens 1–3</h1>
    <p class="lede">Every frame at 390&nbsp;pt, the iPhone logical width. Light and dark follow
      your system setting — switch it to see both.</p>
    <p class="warn">This is not a screenshot and cannot be: the app is SwiftUI and this is HTML.
      It is here to review <strong>the words, the order, and the control types</strong> at true
      width. Do not trust it about spacing, type or colour — that comes from the simulator.
      Both this file and the app's strings are generated from
      <code>Shared/RequestPage/Copy.json</code>, so what you mark up is what ships.</p>
    <div id="sheet">{body}</div>
  </body>
</html>
"""


def main() -> int:
    c = json.loads(SRC.read_text(encoding="utf-8"))
    SWIFT.write_text(gen_swift(c), encoding="utf-8")
    SHEET.write_text(gen_sheet(c), encoding="utf-8")
    print(f"wrote {SWIFT.relative_to(ROOT)} and {SHEET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
