#!/usr/bin/env python3
"""Generate the request-page copy constants and the review contact sheet.

One source (`Shared/RequestPage/Copy.json`), two outputs:

  Shared/RequestPage/Copy.swift   what the app shows
  tools/contact-sheet.html        what Matt marks up

The point of generating both is that a mockup which can drift from the app is
worth less than no mockup at all — you review the wrong words and ship the
right ones. CI runs this and diffs, exactly as the web app does with the dump's
generated type, so the two cannot separate silently.

What the sheet is NOT: a screenshot. It cannot be, because this repository's
UI is SwiftUI and the sheet is HTML. It shows the words, the order, the
control types and the true width. Pixel truth comes from the simulator on a
Mac, and nothing here should be trusted about spacing, type or color.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "Shared" / "RequestPage" / "Copy.json"
SWIFT = ROOT / "Shared" / "RequestPage" / "Copy.swift"
SHEET = ROOT / "tools" / "contact-sheet.html"

BANNER = "// Generated by tools/gen-request-copy.py from Shared/RequestPage/Copy.json.\n// Edit the JSON, re-run the script, commit all three. Do not edit this file.\n"


def swift_string(s: str) -> str:
    """A Swift string literal.

    Control characters have to be escaped, not merely passed through: a copy
    string containing a real newline (JSON's "\\n" is one) would otherwise be
    emitted as a literal line break inside a `"..."` literal, which is a syntax
    error several lines from anything that looks like the cause.
    """
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return '"' + out + '"'


def esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def gen_swift(c: dict) -> str:
    out = [BANNER, "\nimport Foundation\nimport CalMirrorKit\n",
           "\n/// The request-page UI's words. See Copy.json for why they live in one place.\n",
           "enum RequestCopy {\n"]

    d = c["dormantRow"]
    out.append("\n    enum DormantRow {\n")
    for k in ("title", "off", "blurb", "blurbPhone", "inKeychain", "carryOn"):
        out.append(f"        static let {k} = {swift_string(d[k])}\n")
    out.append("        /// The one-liner names the device it is running on, because\n")
    out.append("        /// \"nothing leaves this device\" is the promise and it reads as\n")
    out.append("        /// boilerplate when the device is abstract.\n")
    out.append("        static var blurbForPlatform: String {\n")
    out.append("            #if os(macOS)\n            blurb\n            #else\n            blurbPhone\n            #endif\n        }\n    }\n")

    e = c["explainer"]
    out.append("\n    enum Explainer {\n")
    out.append("        /// One feature row of the first-run sheet: a symbol, a headline,\n")
    out.append("        /// one line. Three of them replace the four paragraphs the explainer\n")
    out.append("        /// used to be (apple/design/native.md, section 1).\n")
    out.append("        struct Feature { let symbol: String; let headline: String; let line: String }\n")
    for k in ("symbol", "title"):
        out.append(f"        static let {k} = {swift_string(e[k])}\n")
    out.append("        static let features: [Feature] = [\n")
    for f in e["features"]:
        out.append(f"            Feature(symbol: {swift_string(f['symbol'])}, headline: {swift_string(f['headline'])}, line: {swift_string(f['line'])}),\n")
    out.append("        ]\n")
    for k in ("footnote", "primary", "secondary"):
        out.append(f"        static let {k} = {swift_string(e[k])}\n")
    out.append("    }\n")

    out.append("\n    enum Calendars {\n")
    for k, v in c["calendars"].items():
        out.append(f"        static let {k} = {swift_string(v)}\n")
    out.append("    }\n")

    out.append("\n    enum Display {\n")
    for k, v in c["display"].items():
        out.append(f"        static let {k} = {swift_string(v)}\n")
    out.append("    }\n")

    out.append("\n    enum Policy {\n")
    for k, v in c["policy"].items():
        out.append(f"        static let {k} = {swift_string(v)}\n")
    out.append("    }\n")

    for name, key in (("Notification", "notification"), ("Conflict", "conflict"),
                      ("Lapse", "lapse"), ("Domains", "domains")):
        out.append(f"\n    enum {name} {{\n")
        for k, v in c[key].items():
            out.append(f"        static let {k} = {swift_string(v)}\n")
        out.append("    }\n")

    out.append("\n    enum Live {\n")
    for k, v in c["live"].items():
        out.append(f"        static let {k} = {swift_string(v)}\n")
    out.append("    }\n")

    out.append("\n    enum Offer {\n")
    for k, v in c["offer"].items():
        out.append(f"        static let {k} = {swift_string(v)}\n")
    out.append("    }\n")

    pv = c["preview"]
    out.append("\n    enum Preview {\n")
    for k in ("section", "countOne", "countMany", "across", "emptyPage", "privacy",
              "emptyDayHeading", "whyHeading", "cappedNote", "stale"):
        out.append(f"        static let {k} = {swift_string(pv[k])}\n")
    # Switches rather than dictionaries: the Kit's enums are closed, so a
    # missing case is a compile error here instead of a blank line in the UI
    # the first time somebody adds a rejection reason.
    out.append("\n        /// Why individual candidates were dropped. Lower-case\n")
    out.append("        /// fragments — they are joined into a sentence.\n")
    out.append("        static func reason(_ r: Rejection) -> String {\n")
    out.append("            switch r {\n")
    for k, v in pv["reasons"].items():
        out.append(f"            case .{k}: return {swift_string(v)}\n")
    out.append("            }\n        }\n")
    out.append("\n        /// Why a whole day was excluded before any time was considered.\n")
    out.append("        static func reason(_ r: DayRejection) -> String {\n")
    out.append("            switch r {\n")
    for k, v in pv["dayReasons"].items():
        out.append(f"            case .{k}: return {swift_string(v)}\n")
    out.append("            }\n        }\n")
    out.append("\n        /// Why the policy itself offers nothing, whatever the calendar says.\n")
    out.append("        static func reason(_ p: PolicyProblem) -> String {\n")
    out.append("            switch p {\n")
    for k, v in pv["problems"].items():
        out.append(f"            case .{k}: return {swift_string(v)}\n")
    out.append("            }\n        }\n")
    out.append("    }\n}\n")
    return "".join(out)


def row(title, caption=None, control="toggle", value=None):
    ctl = {
        "toggle": '<span class="ctl toggle" aria-hidden="true"></span>',
        "check": '<span class="ctl check" aria-hidden="true">✓</span>',
        "chevron": '<span class="ctl chev" aria-hidden="true">›</span>',
        "none": "",
    }[control]
    val = f'<span class="val">{esc(value)}</span>' if value else ""
    cap = f'<p class="cap">{esc(caption)}</p>' if caption else ""
    return (f'<div class="row"><div class="rowmain"><span class="t">{esc(title)}</span>'
            f'{val}{ctl}</div>{cap}</div>')


def field(title, value, caption, ghost=False):
    cls = "val ghost" if ghost else "val"
    cap = f'<p class="cap">{esc(caption)}</p>' if caption else ""
    return (f'<div class="row"><div class="rowmain"><span class="t">{esc(title)}</span>'
            f'<span class="{cls}">{esc(value)}</span></div>{cap}</div>')


def gen_sheet(c: dict) -> str:
    d, e, cal = c["dormantRow"], c["explainer"], c["calendars"]

    s1 = ('<div class="scr"><div class="nav">Calendar Mirror</div>'
          '<div class="grp">'
          + row("Run no sooner than", None, "none", "30 minutes")
          + '</div><div class="grp">'
          + row(d["title"], d["blurbPhone"], "chevron", d["off"])
          + "</div></div>")

    # Native pass (apple/design/native.md): the sheet draws what the app draws
    # now — a one-line footer under each group instead of a caption inside it,
    # no header on a screen's first group, a primary button pinned at the
    # bottom, and the explainer as a first-run sheet of three feature rows.
    def ftr(text):
        return f'<p class="ftr">{esc(text)}</p>'

    def pinned(label):
        return f'<div class="pin"><div class="btn">{esc(label)}</div></div>'

    feats = "".join(
        f'<div class="feat"><span class="sym" aria-hidden="true">◆</span>'
        f'<div><b>{esc(f["headline"])}</b><br><span class="fl">{esc(f["line"])}</span></div></div>'
        for f in e["features"])
    s2 = ('<div class="scr sheet"><div class="pad center">'
          f'<div class="bigsym" aria-hidden="true">◷</div><h3>{esc(e["title"])}</h3></div>'
          f'<div class="pad">{feats}</div>'
          f'<div class="pad"><p class="foot center">{esc(e["footnote"])}</p></div>'
          + pinned(e["primary"])
          + f'<p class="center link">{esc(e["secondary"])}</p></div>')

    cals = [("Home", True, False), ("Work", True, False),
            ("Referee assignments", True, True), ("US Holidays", False, False)]
    rows = ""
    for name, blocking, isreq in cals:
        rows += (f'<div class="calrow"><span class="t">{esc(name)}</span>'
                 f'<span class="pill {"on" if blocking else ""}">{esc(cal["blockTitle"])}</span>'
                 f'<span class="pill {"on" if isreq else ""}">{esc(cal["useTitle"])}</span></div>')
    s3 = ('<div class="scr"><div class="nav">Which calendars</div>'
          f'<div class="grp">{rows}</div>' + ftr(cal["footer"])
          + pinned("Continue") + "</div>")

    dsp, pol, pv = c["display"], c["policy"], c["preview"]

    s4 = ('<div class="scr"><div class="nav">' + esc(dsp["section"]) + "</div>"
          + '<div class="grp">'
          + field(dsp["nameTitle"], "Matt Baylor", None)
          + field(dsp["blurbTitle"], dsp["blurbPlaceholder"], None, ghost=True)
          + "</div>" + ftr(dsp["pageFooter"])
          + '<div class="grp"><div class="hdr">' + esc(dsp["meetingSection"]) + "</div>"
          + field(dsp["titleTitle"], "Meeting", None)
          + field(dsp["locationTitle"], dsp["locationPlaceholder"], None, ghost=True)
          + "</div>" + ftr(dsp["meetingFooter"])
          + pinned("Continue") + "</div>")

    # The sentence, as architecture.md §3 phrases it — the whole point is that
    # it reads aloud, so the sheet has to show it reading aloud.
    sentence = (f'<p class="say"><b>{esc(pol["dayStarts"])}</b> <u>9:00 AM</u> '
                f'<b>{esc(pol["dayEnds"])}</b> <u>5:00 PM</u><br>'
                f'<b>{esc(pol["zoneTitle"])}</b> <u>America/Denver</u><br>'
                f'<b>{esc(pol["lunchTitle"])}</b> <u>12:00</u>–<u>1:30 PM</u><br>'
                f'<b>{esc(pol["weekdaysTitle"])}</b> '
                + "".join(f'<span class="day {"on" if d in "MTWTF" else ""}">{d}</span>'
                          for d in ["S", "M", "T", "W", "T", "F", "S"][0:7])
                + "</p>")
    s5 = ('<div class="scr"><div class="nav">' + esc(pol["section"]) + "</div>"
          + '<div class="grp"><div class="pad14">' + sentence + "</div></div>"
          + ftr(pol["dayFooter"])
          + '<div class="grp">'
          + row(pol["horizonTitle"], None, "none", "14 days")
          + row(pol["maxPerDayTitle"], None, "none", "4")
          + "</div>" + ftr(pol["shapeFooter"])
          + '<div class="grp">'
          + row(pol["noticeTitle"], None, "none", "12 hours")
          + "</div>" + ftr(pol["noticeFooter"])
          + '<div class="grp">'
          + row(pol["slotTitle"], None, "none", "30 min")
          + row(pol["alignTitle"], None, "none", ":00 and :30")
          + row(pol["bufferTitle"], None, "none", "15 min")
          + "</div>" + ftr(pol["offerFooter"])
          + pinned("Continue") + "</div>")

    count = pv["countMany"].replace("%d", "{}").format(11)
    across = pv["across"].replace("%d", "{}").format(14)
    days = [("Mon 21", ["9:00", "10:30", "2:00"]), ("Tue 22", ["9:30", "11:00"]),
            ("Wed 23", []), ("Thu 24", ["9:00", "1:30", "3:00"])]
    grid = ""
    for label, times in days:
        chips = ("".join(f'<span class="slot">{t}</span>' for t in times)
                 or '<span class="empty">nothing offered</span>')
        grid += f'<div class="dayrow"><span class="dl">{esc(label)}</span><span class="chips">{chips}</span></div>'
    s6 = ('<div class="scr"><div class="nav">' + esc(pv["section"]) + "</div>"
          + f'<div class="grp"><div class="pad14"><span class="bignum">{esc(count)}</span> '
          + f'<span class="val">{esc(across)}</span></div>{grid}</div>'
          + ftr(pv["privacy"])
          + '<div class="grp"><div class="hdr">' + esc(pv["emptyDayHeading"]) + "</div>"
          + '<div class="pad14"><p class="body sm"><b>Wed 23</b> — 6 busy, 2 '
          + esc(pv["reasons"]["cappedPerDay"]) + ", 1 " + esc(pv["reasons"]["lunch"])
          + "</p></div></div>" + ftr(pv["cappedNote"])
          + ftr(pv["stale"])
          + pinned("See what it costs") + "</div>")

    off, lv = c["offer"], c["live"]

    def offer_screen(trial):
        price = (off["trialLine"].replace("%@", "{}").format("3 months free", "$19.99")
                 if trial else off["noTrialLine"].replace("%@", "{}").format("$19.99"))
        note = "" if trial else f'<p class="cap">{esc(off["noTrialNote"])}</p>'
        btn = off["buyWithTrial"] if trial else off["buyWithoutTrial"]
        ups = ""
        for name, pr, desc in [
            ("AskWhen.me Custom Subdomain", "$34.99", "Your own name.askwhen.me, and more than one page."),
            ("AskWhen.me Custom Domain", "$69.99", "Your page on your own domain, and several pages.")]:
            ups += (f'<div class="row"><div class="rowmain"><span class="t">{esc(name)}</span>'
                    f'<span class="val">{esc(pr)}</span></div><p class="cap">{esc(desc)}</p></div>')
        return ('<div class="scr"><div class="nav">' + esc(off["section"]) + "</div>"
                + '<div class="grp"><div class="pad14">'
                + f'<h4>{esc(off["heading"])}</h4>'
                + f'<p class="body sm">{esc(off["lede"])}</p></div></div>'
                + '<div class="grp"><div class="pad14">'
                + '<p class="body"><b>AskWhen.me Request Page</b></p>'
                + '<p class="cap">Anyone can ask you for a time. Your calendar stays put.</p>'
                + f'<p class="body" style="margin-top:8px"><b>{esc(price)}</b></p>{note}'
                + f'<div class="btn">{esc(btn)}</div></div></div>'
                + ftr(off["renews"]) + ftr(off["network"])
                + '<div class="grp"><div class="hdr">' + esc(off["upgradesHeading"]) + "</div>"
                + ups + "</div>" + ftr(off["upgradesNote"])
                + '<div class="grp">' + row(off["restore"], None, "none") + "</div></div>")

    s7 = offer_screen(True)
    s7b = offer_screen(False)

    s9 = ('<div class="scr"><div class="nav">' + esc(lv["section"]) + "</div>"
          + '<div class="grp"><div class="pad14">'
          + f'<h4>{esc(lv["heading"])}</h4>'
          + f'<p class="body sm">{esc(lv["lede"])}</p>'
          + '<p class="mono">askwhen.me/x7f2k9</p></div>'
          + row(lv["share"], None, "none") + row(lv["openTitle"], None, "none")
          + "</div>" + ftr(lv["linkFooter"])
          + '<div class="grp"><div class="hdr">' + esc(c["notification"]["permissionHeading"]) + "</div>"
          + row(c["notification"]["permissionAsk"], None, "none") + "</div>"
          + ftr(c["notification"]["permissionFooter"])
          + '<div class="grp"><div class="hdr">' + esc(lv["deviceSection"]) + "</div>"
          + row(lv["publishes"], None, "check") + row(lv["holdsKey"], None, "check")
          + row(lv["turnOff"]) + "</div>" + ftr(lv["deviceFooter"]) + "</div>")

    cells = [
        ("1 · The dormant row", "Off by default. Drawing this costs no network.", s1),
        ("2 · What this is", "A first-run sheet: three feature rows and the cost, before any work is asked for.", s2),
        ("3 · Which calendars count", "Two checkboxes per calendar, where the owner already is.", s3),
        ("4 · Your page", "The one identifying field, and who titles the event.", s4),
        ("5 · Your day", "Asked as a sentence, not a form. Bounds are product decisions.", s5),
        ("6 · What people see", "Real dates from the real calendar, before anyone else sees them.", s6),
        ("7 · Publishing", "The first network request of the app's life, and it is to Apple.", s7),
        ("7b · No trial left", "Apple gives one per person per group. A returning owner must not be promised one.", s7b),
        ("9 · Your page is live", "Where screen 8 lands. The key warning is said once, here.", s9),
    ]
    body = "".join(
        f'<div class="cell"><h2>{esc(t)}</h2><p>{esc(sub)}</p>{scr}</div>'
        for t, sub, scr in cells)

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Request page — contact sheet</title>
    <!-- GENERATED by tools/gen-request-copy.py. Edit Shared/RequestPage/Copy.json. -->
    <style>
      :root {{
        color-scheme: light dark;
        --page: #e8ecf3; --ink: #0d1220; --note: #5a6a80; --edge: #cfd8e6;
        --card: #ffffff; --grp: #f2f3f7; --tint: #0a63d2; --sep: #e3e6ee;
      }}
      @media (prefers-color-scheme: dark) {{
        :root {{
          --page: #06080d; --ink: #e6edf3; --note: #8494a8; --edge: #1c2432;
          --card: #11151d; --grp: #171c26; --tint: #4c9bff; --sep: #232b38;
        }}
      }}
      body {{ margin: 0; background: var(--page); color: var(--ink); padding: 32px 24px 64px;
        font: 15px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }}
      h1 {{ font-size: 20px; margin: 0 0 4px; }}
      .lede {{ color: var(--note); margin: 0 0 8px; max-width: 74ch; }}
      .warn {{ color: var(--note); margin: 0 0 30px; max-width: 74ch; font-size: 13px;
        border-left: 3px solid var(--edge); padding-left: 10px; }}
      #sheet {{ display: grid; grid-template-columns: repeat(auto-fill, 390px);
        justify-content: start; gap: 30px 26px; align-items: start; }}
      .cell h2 {{ font-size: 13px; text-transform: uppercase; letter-spacing: .6px; margin: 0 0 2px; }}
      .cell > p {{ color: var(--note); font-size: 13px; margin: 0 0 10px; }}
      /* 390px is the iPhone 15/16 logical width. Fixed, never stretched: a
         contact sheet whose frames resize is lying about the phone. */
      .scr {{ width: 390px; box-sizing: border-box; background: var(--grp);
        border: 1px solid var(--edge); border-radius: 12px; overflow: hidden; }}
      .nav {{ padding: 12px 16px; font-weight: 600; font-size: 17px;
        border-bottom: 1px solid var(--sep); background: var(--card); }}
      .back {{ color: var(--tint); font-weight: 400; font-size: 16px; }}
      .grp {{ background: var(--card); margin: 14px 0; border-top: 1px solid var(--sep);
        border-bottom: 1px solid var(--sep); }}
      .hdr {{ font-size: 12px; text-transform: uppercase; letter-spacing: .5px;
        color: var(--note); padding: 14px 16px 6px; }}
      .row {{ padding: 11px 16px; border-bottom: 1px solid var(--sep); }}
      .row:last-child {{ border-bottom: 0; }}
      .rowmain {{ display: flex; align-items: center; gap: 8px; }}
      .t {{ flex: 1; }}
      .val {{ color: var(--note); }}
      .ctl.toggle {{ width: 42px; height: 25px; border-radius: 13px; background: var(--sep); }}
      .ctl.chev {{ color: var(--note); font-size: 20px; }}
      .cap {{ color: var(--note); font-size: 12.5px; margin: 6px 0 0; }}
      .pad8 {{ padding: 0 16px 10px; }}
      .priv {{ border-top: 1px solid var(--sep); padding-top: 10px; }}
      .pad {{ padding: 18px 20px 24px; background: var(--card); }}
      h3 {{ font-size: 24px; line-height: 1.2; margin: 4px 0 14px; }}
      .body {{ font-size: 15px; margin: 0 0 12px; }}
      .sub {{ font-size: 12px; text-transform: uppercase; letter-spacing: .5px;
        color: var(--note); margin: 20px 0 6px; }}
      .btn {{ background: var(--tint); color: #fff; text-align: center; padding: 14px;
        border-radius: 10px; font-weight: 600; margin: 22px 0 12px; }}
      .foot {{ color: var(--note); font-size: 12.5px; margin: 0; }}
      .calrow {{ display: flex; align-items: center; gap: 6px; padding: 10px 16px;
        border-bottom: 1px solid var(--sep); }}
      .pill {{ font-size: 11px; padding: 3px 8px; border-radius: 99px; white-space: nowrap;
        border: 1px solid var(--sep); color: var(--note); }}
      .pill.on {{ background: var(--tint); border-color: var(--tint); color: #fff; }}
      .ghost {{ opacity: .5; }}
      .pad14 {{ padding: 14px 16px; }}
      .say {{ font-size: 16px; line-height: 2; margin: 0 0 10px; }}
      .say u {{ text-decoration: none; border-bottom: 1.5px dashed var(--tint);
        color: var(--tint); padding: 1px 3px; }}
      .day {{ display: inline-block; width: 24px; height: 24px; line-height: 24px;
        text-align: center; border-radius: 99px; font-size: 12px; margin-right: 3px;
        background: var(--sep); color: var(--note); }}
      .day.on {{ background: var(--tint); color: #fff; }}
      h4 {{ font-size: 17px; margin: 0 0 4px; }}
      .body.sm {{ font-size: 13.5px; margin: 0 0 6px; }}
      .dayrow {{ display: flex; gap: 10px; align-items: baseline; padding: 9px 16px;
        border-top: 1px solid var(--sep); }}
      .dl {{ width: 58px; color: var(--note); font-size: 13px; flex: none; }}
      .chips {{ display: flex; flex-wrap: wrap; gap: 5px; }}
      .slot {{ font-size: 12.5px; padding: 3px 9px; border-radius: 6px;
        border: 1px solid var(--tint); color: var(--tint); }}
      .empty {{ font-size: 12.5px; color: var(--note); font-style: italic; }}
      .mono {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 18px;
        margin: 14px 0 0; word-break: break-all; }}
      .link {{ color: var(--tint); }}
      /* Native pass: footers sit under the group, outside the card. */
      .ftr {{ color: var(--note); font-size: 12.5px; margin: -8px 0 14px; padding: 0 16px; }}
      .pin {{ padding: 8px 16px 6px; background: var(--grp); }}
      .pin .btn {{ margin: 0; }}
      .center {{ text-align: center; }}
      .sheet {{ background: var(--card); }}
      .bigsym {{ font-size: 44px; color: var(--tint); line-height: 1; margin: 18px 0 6px; }}
      .feat {{ display: flex; gap: 14px; align-items: flex-start; margin: 0 0 16px; }}
      .feat .sym {{ color: var(--tint); font-size: 22px; line-height: 1.2; width: 28px; text-align: center; }}
      .fl {{ color: var(--note); font-size: 13.5px; }}
      .bignum {{ font-size: 28px; font-weight: 700; letter-spacing: -.5px; }}
    </style>
  </head>
  <body>
    <h1>Request page — setup, screens 1–9</h1>
    <p class="lede">Every frame at 390&nbsp;pt, the iPhone logical width. Light and dark follow
      your system setting — switch it to see both.</p>
    <p class="warn">This is not a screenshot and cannot be: the app is SwiftUI and this is HTML.
      It is here to review <strong>the words, the order, and the control types</strong> at true
      width. Do not trust it about spacing, type or color — that comes from the simulator.
      Both this file and the app's strings are generated from
      <code>Shared/RequestPage/Copy.json</code>, so what you mark up is what ships.</p>
    <div id="sheet">{body}</div>
  </body>
</html>
"""


def main() -> int:
    c = json.loads(SRC.read_text(encoding="utf-8"))
    SWIFT.write_text(gen_swift(c), encoding="utf-8")
    SHEET.write_text(gen_sheet(c), encoding="utf-8")
    print(f"wrote {SWIFT.relative_to(ROOT)} and {SHEET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
